# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          
      - name: get pkg name & version
        id: pkg
        run: |
          name=$(node -e 'console.log(require("./package.json").name)')
          version=$(node -e 'console.log(require("./package.json").version)')
          echo "name=$name" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          
      - run: npm ci
      
      - name: publish if new version
        run: |
          PKG="${{ steps.pkg.outputs.name }}"
          VER="${{ steps.pkg.outputs.version }}"
          echo "Checking if $PKG@$VER exists..."
          if npm view "${PKG}@${VER}" >/dev/null 2>&1; then
            echo "Package version $VER already published — skipping publish (success)."
          else
            echo "Publishing $PKG@$VER..."
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
